name: Build for Windows

on:
  workflow_dispatch:

env:
    LLVM_VER: 16.0.6
    BRANCH: llvmorg-16.0.6

jobs:

   build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        # ninja version to download. Default: 1.10.0
        version: 1.10.0
        dest: ${{ github.workspace }}/ninja_bin

    - name: Clone LLVM
      uses: actions/checkout@v3
      with:
        repository: 'llvm/llvm-project'
        ref: ${{ env.BRANCH }}
        path: 'llvm-project-${{ env.LLVM_VER }}'
        fetch-depth: 1


    - name: Configure CMake
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 &^
        cmake -GNinja -S llvm-project-%LLVM_VER%\llvm -B llvm-build -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="/machine:x64" -DCMAKE_INSTALL_PREFIX="%GITHUB_WORKSPACE%/llvm-install-%LLVM_VER%/"

    - name: Build
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 &^
        ninja -C llvm-build clang install

    - name: Cache LibClang
      id: cache-clang
      uses: actions/cache@v3
      with:
        path: 'llvm-install-${{ env.LLVM_VER }}/'
        key: 'libclang-${{ runner.os }}-${{ env.LLVM_VER }}'
    - name: build
      uses: actions/checkout@v3
    - run: cmake -B build -GNinja -DCMAKE_CXX_COMPILER=clang++-15
    - run: cmake --build build
    - uses: actions/upload-artifact@v3
      with:
          name: jakt
          path: build
